# Generated by Django 2.2.3 on 2019-08-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_name',
            field=models.TextField(default='Unknown'),
        ),
    ]
